export const menuItemsData = [
  {
    id: 1,
    name: 'Pasta',
    info: "Only thing I am testing positive for is Pasta or Cheese. ",
    price: 26,
    img: "/images/pasta.jpg",
  },
  {
    id: 2,
    name: 'Rice',
    info: 'Rice is great if you are really hungry and want to eat two thousand of something.',
    price: 34,
    img: "/images/rice.jpg",
  },
  {
    id: 3,
    name: 'Bread',
    info: 'I just want to make bread and snuggle with it.',
    price: 14,
    img: "/images/bread.jpg",
  },
  {
    id: 4,
    name: 'All-Purpose-Flour',
    info: 'Talent is like a little seed; when nurtured, it will flourish.',
    price: 70,
    img: "/images/flour.jpg",
  },
  {
    id: 5,
    name: 'Breakfast-Cereal',
    info: 'For whatever reason, I enjoy eating soggy cereal.',
    price: 44,
    img: "/images/breakfastcereal.jpg",
  },

  // Dairy Products
  {
    id: 6,
    name: 'Milk',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/milk.jpg",
  },
  {
    id: 7,
    name: 'Milk Badam',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/milkbadam.jpg",
  },
  {
    id: 8,
    name: 'Condensed Milk',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/condensedmilk.jpg",
  },
  {
    id: 9,
    name: 'Kefir Milk',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/kefirmilk.jpg",
  },
  {
    id: 10,
    name: 'Hidde valley Butter Milk',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/buttermilk.jpg",
  },
  {
    id: 11,
    name: 'Goat Milk',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/goatmilk.jpg",
  },
  {
    id: 12,
    name: 'Iced Pop',
    info: 'If you do not milk the cow fully, it falls sick.',
    price: 20,
    img: "/images/icedpop.jpg",
  },
  {
    id: 13,
    name: 'AlmondMilk',
    info: 'Apple diet is not the worst choice.',
    price: 90,
    img: "/images/almondmilk.jpg",
  },
  {
    id: 14,
    name: 'Cheese',
    info: 'Good cheese needs good companions.',
    price: 50,
    img: "/images/cheese.jpg",
  },
  {
    id: 15,
    name: 'Egg',
    info: 'Boredom is the dream bird that hatches the egg of experience.',
    price: 30,
    img: "/images/eggs.jpg",
  },
  {
    id: 16,
    name: 'Yogurt',
    info: 'Don’t cry over spilled milk.',
    price: 10,
    img: "/images/yogurt.jpg",
  },
  {
    id: 17,
    name: 'Sour Cream',
    info: 'Don’t cry over spilled milk.',
    price: 40,
    img: "/images/sourcream.jpg",
  },
  {
    id: 18,
    name: 'Whipped Cream',
    info: 'Don’t cry over spilled milk.',
    price: 90,
    img: "/images/whipped cream.jpg",
  },
  {
    id: 19,
    name: 'Powdered Milk',
    info: 'Don’t cry over spilled milk.',
    price: 60,
    img: "/images/powdermilk.jpg",
  },
  {
    id: 20,
    name: 'Hot Chocolate',
    info: 'Don’t cry over spilled milk.',
    price: 190,
    img: "/images/hotchocolate.jpg",
  },
  {
    id: 21,
    name: 'Almond Milk',
    info: 'Don’t cry over spilled milk.',
    price: 110,
    img: "/images/almondmilk.jpg",
  },
  {
    id: 22,
    name: 'Pudding',
    info: 'Don’t cry over spilled milk.',
    price: 100,
    img: "/images/pudding.jpg",
  },
  {
    id: 23,
    name: 'MilkShake',
    info: 'Don’t cry over spilled milk.',
    price: 175,
    img: "/images/milkshake.jpg",
  },
  {
    id: 24,
    name: 'Whey',
    info: 'Don’t cry over spilled milk.',
    price: 1000,
    img: "/images/whey.jpg",
  },
  {
    id: 25,
    name: 'Ghee',
    info: 'Don’t cry over spilled milk.',
    price: 245,
    img: "/images/ghee.jpg",
  },
  {
    id: 26,
    name: 'Butter',
    info: 'Sweets to the sweet.',
    price: 40,
    img: "/images/butter.jpg",
  },
  {
    id: 27,
    name: 'Peanut Butter',
    info: 'Let there be work, bread, water and salt for all.',
    price: 24,
    img: "/images/peanutbutter.jpg",
  },
  // Fruits
  {
    id: 28,
    name: 'Apple',
    info: 'Apple diet is not the worst choice.',
    price: 90,
    img: "/images/apples.jpg",
  },
  {
    id: 29,
    name: 'Avacado',
    info: 'Sweets to the sweet.',
    price: 140,
    img: "/images/avacado.jpg",
  },
  {
    id: 30,
    name: 'Green Grapes',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/greengrapes.jpg",
  },
  {
    id: 31,
    name: 'Black Grapes',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/blackgrapes.jpg",
  },
  {
    id: 32,
    name: 'Mango',
    info: 'I think that the heart is a lot like those wonderful fruit, like  mangoes',
    price: 100,
    img: "/images/mango.jpg",
  },
  {
    id: 33,
    name: 'GreenApple',
    info: 'WHEN WE THROW ANYTHING AWAY IT MUST GO SOMEWHERE.”',
    price: 64,
    img: "/images/greenappple.jpg",
  },
  {
    id: 34,
    name: 'Kiwi',
    info: 'When the Kiwis ran onto the field we could see the poor bastards were shitting themselves.',
    price: 64,
    img: "/images/kiwi.jpg",
  },
  {
    id: 35,
    name: 'Orange',
    info: 'Orange is a fruit, as sweet as a singing flute.',
    price: 34,
    img: "/images/orange.jpg",
  },
  {
    id: 36,
    name: 'Pineapple',
    info: 'A pineapple a day keeps the worries away.',
    price: 24,
    img: "/images/pineapple.jpg",
  },
  {
    id: 37,
    name: 'Pomengranate',
    info: 'Her cheeks were bright with a soft vermilion of the pomegranate mingling with the whiteness of the lily. ',
    price: 24,
    img: "/images/pomengranate.jpg",
  },
  {
    id: 38,
    name: 'Banana',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/banana.jpg",
  },
  {
    id: 39,
    name: 'BlueBerries',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/blueberries.jpg",
  },
  {
    id: 40,
    name: 'Strawberries',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/straberries.jpg",
  },
  {
    id: 41,
    name: 'Watermelon',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/watermelon.jpg",
  },
  {
    id: 42,
    name: 'Pear',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/pear.jpg",
  },
  {
    id: 43,
    name: 'Guava',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/guava.jpg",
  },
  {
    id: 44,
    name: 'Dragon Fruit',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/dragonfruit.jpg",
  },
  {
    id: 45,
    name: 'Cherry',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/cherry.jpg",
  },
  {
    id: 46,
    name: 'Blackberry',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/blackberries.jpg",
  },
  {
    id: 47,
    name: 'Peach',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/peach.jpg",
  },
  {
    id: 48,
    name: 'Coconut',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/coconut.jpg",
  },
  {
    id: 49,
    name: 'Litchi',
    info: 'Sweets to the sweet.',
    price: 430,
    img: "/images/litchi.jpg",
  },

  // Vegetables

  {
    id: 50,
    name: 'Onion',
    info: 'Life is like an onion. You peel it off one layer at a time, and sometimes you weep.',
    price: 49,
    img: "/images/onion.jpg",
  },
  {
    id: 51,
    name: 'Garlic',
    info: 'Stop and smell the garlic! ',
    price: 28,
    img: "/images/garlic.jpg",
  },
  {
    id: 52,
    name: 'Tomato',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 24,
    img: "/images/tomato.jpg",
  },
  {
    id: 53,
    name: 'Cabbage',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 24,
    img: "/images/cabbage.jpg",
  },
  {
    id: 54,
    name: 'Cauliflower',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 14,
    img: "/images/cauliflower.jpg",
  },
  {
    id: 55,
    name: 'Broccoli',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 54,
    img: "/images/broccoli.jpg",
  },
  {
    id: 56,
    name: 'Carrot',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 24,
    img: "/images/carrot.jpg",
  }, {
    id: 57,
    name: 'Pumpkin',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 34,
    img: "/images/pumpkin.jpg",
  },
  {
    id: 58,
    name: 'Corn',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 24,
    img: "/images/corn.jpg",
  },
  {
    id: 59,
    name: 'Sweet Potato',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 214,
    img: "/images/sweetpotato.jpg",
  },
  {
    id: 60,
    name: 'Yellow Capsicum',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 19,
    img: "/images/yellowcapsicum.jpg",
  },
  {
    id: 61,
    name: 'Red Capsicum',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 14,
    img: "/images/redcapsicum.jpg",
  },
  {
    id: 62,
    name: 'Green Capsicum',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 24,
    img: "/images/greencapsicum.jpg",
  },
  {
    id: 63,
    name: 'Cucumber',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 34,
    img: "/images/cucumber.jpg",
  },
  {
    id: 64,
    name: 'Green Beans',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 14,
    img: "/images/greenbeans.jpg",
  },
  {
    id: 65,
    name: 'Egg Plant',
    info: 'Knowledge is knowing that a tomato is a fruit.',
    price: 20,
    img: "/images/eggplant.jpg",
  },
  {
    id: 66,
    name: 'Peas',
    info: 'Watch the little things in life, the ones you have control over.',
    price: 35,
    img: "/images/peas.jpg",
  },

  // condimentals
  {
    id: 67,
    name: 'Salt',
    info: 'Let there be work, bread, water and salt for all.',
    price: 53,
    img: "/images/salt.jpg",
  },
  {
    id: 68,
    name: 'Ketchup',
    info: 'Let there be work, bread, water and salt for all.',
    price: 60,
    img: "/images/ketchup.jpg",
  },
  {
    id: 69,
    name: 'Mayonnaise',
    info: 'Let there be work, bread, water and salt for all.',
    price: 24,
    img: "/images/mayo.jpg",
  },

  {
    id: 70,
    name: 'BlackPepper',
    info: 'My heart is small, like a love of buttons or black pepper.',
    price: 20,
    img: "/images/blackpepper.jpg",
  },
  {
    id: 71,
    name: 'Redpepper',
    info: 'That red carpet has to be felt to be believed.',
    price: 24,
    img: "/images/redpepper.jpg",
  },
  {
    id: 72,
    name: 'Oregano',
    info: 'Oregano is the spice of life.',
    price: 24,
    img: "/images/oregano.jpg",
  },
  {
    id: 73,
    name: 'Cinnamon',
    info: 'Oregano is the spice of life.',
    price: 44,
    img: "/images/cinnamon.jpg",
  },
  {
    id: 74,
    name: 'Cloves',
    info: 'Oregano is the spice of life.',
    price: 40,
    img: "/images/cloves.jpg",
  },
  {
    id: 75,
    name: 'Fenugreek Seeds',
    info: 'Oregano is the spice of life.',
    price: 24,
    img: "/images/fenugreekseed.jpg",
  },
  {
    id: 76,
    name: 'Turmeric',
    info: 'Oregano is the spice of life.',
    price: 35,
    img: "/images/turmeric.jpg",
  },
  {
    id: 77,
    name: 'Mustard Seeds',
    info: 'Oregano is the spice of life.',
    price: 60,
    img: "/images/mustardseed.jpg",
  },
  {
    id: 78,
    name: 'Saffron',
    info: 'Oregano is the spice of life.',
    price: 264,
    img: "/images/saffron.jpg",
  },
  {
    id: 79,
    name: 'Cocktail Sauce',
    info: 'Oregano is the spice of life.',
    price: 240,
    img: "/images/cocktailsauce.jpg",
  },
  {
    id: 80,
    name: 'Honey',
    info: 'art Words make no Friends: a spoonful of honey will catch more flies than Gallon of Vinegar.',
    price: 200,
    img: "/images/honey.jpg",
  },
  {
    id: 81,
    name: 'vinegar',
    info: 'Sour power vinegar tits sucking on lemon.',
    price: 24,
    img: "/images/vinegar.jpg",
  },
  {
    id: 82,
    name: 'Sugar',
    info: 'Sweets to the sweet.',
    price: 284,
    img: "/images/sugar.jpg",
  }, {
    id: 83,
    name: 'Chopped Tomatoes',
    info: 'Sweets to the sweet.',
    price: 320,
    img: "/images/choppedtomato.jpg",
  },
  {
    id: 84,
    name: 'Cooking Oil',
    info: 'Sweets to the sweet.',
    price: 350,
    img: "/images/oil.jpg",
  },

  // Daals

  {
    id: 85,
    name: 'Red kidney',
    info: 'Sweets to the sweet.',
    price: 406,
    img: "/images/redkidney.jpg",
  },

  {
    id: 86,
    name: 'Cookies',
    info: 'Sweets to the sweet.',
    price: 199,
    img: "/images/cookies.jpg",
  },
  {
    id: 87,
    name: 'Macroni',
    info: 'Sweets to the sweet.',
    price: 315,
    img: "/images/macroni.jpg",
  },
  {
    id: 88,
    name: 'Noodles',
    info: 'Sweets to the sweet.',
    price: 330,
    img: "/images/noodles.jpg",
  },
  // Dry Fruits
  {
    id: 89,
    name: '2Almonds',
    info: 'Sweets to the sweet.',
    price: 700,
    img: "/images/almond.jpg",
  },
  {
    id: 90,
    name: 'Raisins',
    info: 'Sweets to the sweet.',
    price: 500,
    img: "/images/raisins.jpg",
  },
  {
    id: 91,
    name: "Cashew",
    info: 'Sweets to the sweet.',
    price: 490,
    img: "/images/cashew.jpg",
  },
  {
    id: 91,
    name: "Walnuts",
    info: 'Sweets to the sweet.',
    price: 490,
    img: "/images/walnuts.jpg",
  },

];
